# Generated by Django 5.1.8 on 2025-07-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'performance_level',
            },
        ),
        migrations.RemoveIndex(
            model_name='level',
            name='level_interna_1e637c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('source_level_id', 'source_website', 'name')},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='levels',
        ),
        migrations.AddField(
            model_name='performancelevel',
            name='level',
            field=models.ForeignKey(db_column='internal_level_id', on_delete=django.db.models.deletion.CASCADE, to='scrapers.level'),
        ),
        migrations.AddField(
            model_name='performancelevel',
            name='performance',
            field=models.ForeignKey(db_column='internal_performance_id', on_delete=django.db.models.deletion.CASCADE, to='scrapers.performance'),
        ),
        migrations.RemoveField(
            model_name='level',
            name='venue_id',
        ),
        migrations.AddIndex(
            model_name='performancelevel',
            index=models.Index(fields=['performance'], name='performance_interna_1c99d6_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelevel',
            index=models.Index(fields=['level'], name='performance_interna_1c598b_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelevel',
            index=models.Index(fields=['display_order'], name='performance_display_dce370_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancelevel',
            unique_together={('performance', 'level')},
        ),
    ]
