# Generated by Django 5.1.8 on 2025-07-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_performancelevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='price_markup_type',
            field=models.CharField(blank=True, choices=[('dollar', 'Dollar Amount'), ('percentage', 'Percentage')], help_text='Type of price markup applied to tickets', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_markup_updated_at',
            field=models.DateTimeField(blank=True, help_text='When price markup was last updated', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_markup_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of the markup (dollar amount or percentage)', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['price_markup_type'], name='venue_price_m_ce9266_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['price_markup_updated_at'], name='venue_price_m_69bdff_idx'),
        ),
    ]
