# Generated by Django 4.2.11 on 2025-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_add_venue_markup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='pos_enabled',
            field=models.BooleanField(default=False, help_text='Enable POS (Point of Sale) integration for this venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='pos_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When POS was last enabled/disabled for this venue', null=True),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['pos_enabled'], name='venue_pos_ena_aeba24_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['pos_enabled_at'], name='venue_pos_ena_cb8f99_idx'),
        ),
    ]
