# Generated by Django 4.2.11 on 2025-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_add_venue_pos_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='pos_disabled_at',
            field=models.DateTimeField(blank=True, help_text='When POS was disabled for this performance', null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='pos_enabled',
            field=models.BooleanField(default=False, help_text='Enable POS (Point of Sale) integration for this performance'),
        ),
        migrations.AddField(
            model_name='performance',
            name='pos_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When POS was enabled for this performance', null=True),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['pos_enabled'], name='performance_pos_ena_ba876a_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['pos_enabled_at'], name='performance_pos_ena_78042f_idx'),
        ),
    ]
