# Generated by Django 5.1.8 on 2025-07-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0007_populate_four_dimensional_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatpack',
            unique_together={('zone_id', 'row_label', 'start_seat_number', 'end_seat_number', 'scrape_job_key', 'level')},
        ),
    ]
