# Generated by Django 5.1.8 on 2025-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_add_level_to_seat_pack_unique_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seatpack',
            name='seat_pack_is_acti_sync_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatpack',
            name='seat_pack_creation_event_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatpack',
            name='seat_pack_sync_status_idx',
        ),
        migrations.RemoveField(
            model_name='seatpack',
            name='creation_event',
        ),
        migrations.RemoveField(
            model_name='seatpack',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='performance',
            name='pos_sync_enabled',
            field=models.BooleanField(default=False, help_text='Whether POS sync is enabled for this performance'),
        ),
        migrations.AlterField(
            model_name='seatpack',
            name='manually_delisted',
            field=models.BooleanField(default=False),
        ),
    ]
