# Generated by Django 5.1.8 on 2025-07-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0012_make_level_venue_required_update_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='level',
            new_name='level_interna_1e637c_idx',
            old_name='level_venue_id_idx',
        ),
        migrations.RenameIndex(
            model_name='level',
            new_name='level_alias_f307ee_idx',
            old_name='level_alias_idx',
        ),
        migrations.AlterUniqueTogether(
            name='seatpack',
            unique_together={('zone_id', 'row_label', 'start_seat_number', 'end_seat_number', 'scrape_job_key', 'level', 'section')},
        ),
    ]
