# Generated by Django 4.2.11 on 2025-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0013_rename_level_venue_id_idx_level_interna_1e637c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='User-friendly alias for the section name', max_length=255),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['alias'], name='section_alias_556ab0_idx'),
        ),
    ]
