# Generated by Django 5.1.8 on 2025-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0014_add_section_alias_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperdefinition',
            name='name',
            field=models.CharField(help_text='Unique scraper name (e.g., washington_pavilion_scraper)', max_length=100),
        ),
    ]
